build:
  image: arvitaly/electron-go:latest
  commands:
    - go get
    - go build
    - go test
    - go get github.com/arvitaly/gopherjs-jasmine
    - npm install
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm test --
