language: go
go:
    - 1.5
node_js:
    - "0.12.7"
sudo: false
addons:
  apt:
    packages:
      - xvfb
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install electron-prebuilt -g
  - go get github.com/arvitaly/gopherjs-jasmine
  - go get -u github.com/gopherjs/gopherjs
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
  - npm test
